// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTae0z_U6O_6YkyblADZgUMytWIIAipZA',
    appId: '1:382422564484:web:06c310489199aa2d350cd1',
    messagingSenderId: '382422564484',
    projectId: 'vcon-app-2024',
    authDomain: 'vcon-app-2024.firebaseapp.com',
    storageBucket: 'vcon-app-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jHP367jWUkB-BL11MlHTVjKRMM19n7Q',
    appId: '1:382422564484:android:a769cf0bb0bac89f350cd1',
    messagingSenderId: '382422564484',
    projectId: 'vcon-app-2024',
    storageBucket: 'vcon-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjkafgBFYucgQ8brGOq7SedG-ZX0cVVDc',
    appId: '1:382422564484:ios:da07c32fcb401615350cd1',
    messagingSenderId: '382422564484',
    projectId: 'vcon-app-2024',
    storageBucket: 'vcon-app-2024.appspot.com',
    iosBundleId: 'com.example.vconTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjkafgBFYucgQ8brGOq7SedG-ZX0cVVDc',
    appId: '1:382422564484:ios:da07c32fcb401615350cd1',
    messagingSenderId: '382422564484',
    projectId: 'vcon-app-2024',
    storageBucket: 'vcon-app-2024.appspot.com',
    iosBundleId: 'com.example.vconTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTae0z_U6O_6YkyblADZgUMytWIIAipZA',
    appId: '1:382422564484:web:8e0e7d75f9cbf8f1350cd1',
    messagingSenderId: '382422564484',
    projectId: 'vcon-app-2024',
    authDomain: 'vcon-app-2024.firebaseapp.com',
    storageBucket: 'vcon-app-2024.appspot.com',
  );
}
